site_name: Kanbanize-sdk
repo_url: https://github.com/darcivieira/kanbanize-sdk
repo_name: Kanbanize-sdk
edit_uri: tree/main

theme:
  name: material

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [kanbanize_sdk]